<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7uOm4M9' shared service.

return $this->privates['.service_locator.7uOm4M9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SecurityController::index' => ['privates', '.service_locator.IOBupq0', 'get_ServiceLocator_IOBupq0Service.php', true],
    'App\\Controller\\SecurityController::suppression' => ['privates', '.service_locator..NmEFk5', 'get_ServiceLocator__NmEFk5Service.php', true],
    'App\\Controller\\SecurityController:index' => ['privates', '.service_locator.IOBupq0', 'get_ServiceLocator_IOBupq0Service.php', true],
    'App\\Controller\\SecurityController:suppression' => ['privates', '.service_locator..NmEFk5', 'get_ServiceLocator__NmEFk5Service.php', true],
], [
    'App\\Controller\\SecurityController::index' => '?',
    'App\\Controller\\SecurityController::suppression' => '?',
    'App\\Controller\\SecurityController:index' => '?',
    'App\\Controller\\SecurityController:suppression' => '?',
]);
