<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIHJpRhn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIHJpRhn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIHJpRhn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIHJpRhn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIHJpRhn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IHJpRhn',
    'container.build_id' => '5eac4c6e',
    'container.build_time' => 1576860753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIHJpRhn');
